name: kana_to_kanji
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^8.1.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  path: ^1.8.3
  sqflite: ^2.2.8+4
  stacked: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/database/
