name: kana_to_kanji
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.3.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^10.1.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  path: ^1.8.3
  sqflite: ^2.2.8+4
  stacked: ^3.4.0
  rive: ^0.11.14
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/database/
    - assets/animations/

  fonts:
    - family: MPlusRounded1c
      fonts:
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/MPLUSRounded1c/MPLUSRounded1c-Black.ttf
          weight: 900
          style: normal

flavorizr:
  app:
    name: "Kanaとkanji"
  flavors:
    main:
      app:
        name: "Kanaとkanji"
      android:
        applicationId: "dev.xavierc.kana_to_kanji"
      ios:
        bundleId: "dev.xavierc.kana_to_kanji"
    beta:
      app:
        name: "Kanaとbeta"
      ios:
        bundleId: "dev.xavierc.kana-to-kanji.beta"
    dev:
      app:
        name: "Kanaとdev"
      ios:
        bundleId: "dev.xavierc.kana-to-kanji.dev"